# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Corretor dos testes unitários

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configuração de Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Instalando Pytest
        if: always()
        run: |
           pip install pytest
      - name: Correção do desafio FizzBuzz
        if: always()
        run: |
          pytest -v tests/tests_fizz_buzz.py
      - name: Correção do desafio Contando as letras dos números
        if: always()
        run: |
          pytest -v tests/tests_contando_letras_numeros.py
      - name: Correção do desafio Entre Letras
        if: always()
        run: |
          pytest -v tests/tests_entre_letras.py
      - name: Correção do desafio criptografia
        if: always()
        run: |
          pytest -v tests/tests_criptografia.py